name: Test secret
on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        run:
          echo $ENV_SECRET
        env:
          ENV_SECRET: ${{ secrets.TestSecret }}
